### ISSUE TITLE
Masked Links

### ISSUE THREAD

**Issue by Prynce2015** [TheBastionBot/embedbuilder#4]
This is a Request.

Please add a way for us to generate multiple masked links on fields on Bastion's Embed Builder.

Thank you.

**Comment by iamtraction** [comment]
By masked links do you mean [this]()?

**Comment by Prynce2015** [comment]
Yes, that's exactly what I meant.

**Comment by iamtraction** [comment]
Well, I don't see a need for creating an builder for links. It can simply be created using `[placing text here](and the link here)`, which will give you the output as: [placing text here](https://example.com).
